#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
bili_split.py — B站视频按时间戳分段 + FLAC 提取 + Whisper 歌词转写 + 歌词嵌入 + 主题命名

成熟工作流（两阶段）:
  阶段一 split : yt-dlp 下载最佳音轨 -> 按时间戳精确切割为 flac -> faster-whisper 逐段转写歌词
                产出: seg_XX.flac / seg_XX.txt / cuts.json / themes.json(空主题模板)
  阶段二 apply : 读取 themes.json(人工或 AI 填好主题) -> 重命名为 "NN_主题.flac"
                -> 用 ffmpeg 把 LYRICS/TITLE/ARTIST/COMMENT 标签嵌入 flac

用法:
  python bili_split.py split  --url "https://www.bilibili.com/video/BVxxxx" \
      --cuts "0:00-12:34, 12:34-25:00, 25:00-40:12" \
      --model small --out ./output [--browser edge]

  python bili_split.py apply  --out ./output [--themes themes.json]

  python bili_split.py selftest --model tiny   # 不联网, 合成音频验证全链路

依赖: yt-dlp, ffmpeg, faster-whisper (pip install faster-whisper)
"""

import argparse
import json
import os
import re
import shutil
import socket
import subprocess
import sys
import tempfile
import urllib.request
import wave

# ---- 工具路径解析（环境变量 > PATH，无硬编码本机路径）----
# 可设置: FFMPEG_PATH / YTDLP_PATH / NODE_PATH 指向本机工具
def _tool_path(env_name):
    v = os.environ.get(env_name, "").strip()
    return v or None


FFMPEG_DEFAULT = _tool_path("FFMPEG_PATH")
YTDLP_DEFAULT = _tool_path("YTDLP_PATH")
NODE_DEFAULT = _tool_path("NODE_PATH")

# HuggingFace 模型走国内镜像（首次下载模型时显著加速）
os.environ.setdefault("HF_ENDPOINT", "https://hf-mirror.com")

TS_RE = re.compile(r"^(\d{1,2}:)?(\d{1,2}):(\d{1,2}(?:\.\d+)?)$")


def log(msg):
    print(f"[bili_split] {msg}", flush=True)


def find_exe(name, given, default):
    if given:
        return given
    cands = [default, shutil.which(name)]
    for c in cands:
        if c and os.path.exists(c):
            return c
    env_hint = {"ffmpeg": "FFMPEG_PATH", "yt-dlp": "YTDLP_PATH",
                "node": "NODE_PATH"}.get(name, name.upper() + "_PATH")
    raise SystemExit(
        f"找不到 {name}。请确保已加入 PATH，或设置环境变量 {env_hint}，或用 --{name} 参数指定路径")


def parse_ts(s):
    """'12:34' / '1:02:03.5' -> 秒(float)"""
    m = TS_RE.match(s.strip())
    if not m:
        raise ValueError(f"时间戳格式错误: {s!r} (应为 mm:ss 或 hh:mm:ss)")
    h = int(m.group(1)[:-1]) if m.group(1) else 0
    mi = int(m.group(2))
    se = float(m.group(3))
    return h * 3600 + mi * 60 + se


def parse_cuts(spec):
    """'0:00-12:34, 12:34-25:00' -> [(start, end), ...] 并校验"""
    pairs = []
    for item in spec.split(","):
        item = item.strip()
        if not item:
            continue
        if "-" not in item:
            raise ValueError(f"分段 {item!r} 缺少 '-'，格式应为 起止-结束")
        a, b = item.split("-", 1)
        s, e = parse_ts(a), parse_ts(b)
        if e <= s:
            raise ValueError(f"分段 {item!r} 结束时间必须大于开始时间")
        pairs.append((s, e))
    for i in range(1, len(pairs)):
        if pairs[i][0] < pairs[i - 1][1] - 0.5:
            log(f"警告: 分段{i}与{i-1}时间重叠 ({pairs[i-1][1]} > {pairs[i][0]})")
    return pairs


def run(cmd, **kw):
    log("$ " + " ".join(cmd))
    return subprocess.run(cmd, check=True, **kw)


def ffmpeg_cmd(exe, args):
    return [exe, "-hide_banner", "-loglevel", "error", "-y"] + args


def cut_flac(ffmpeg, src_wav, out_flac, start, end):
    """从解码后的 wav 精确切割为 flac（-ss/-to 放 -i 前, 采样级精确）"""
    run(ffmpeg_cmd(ffmpeg, ["-ss", f"{start:.3f}", "-to", f"{end:.3f}",
                            "-i", src_wav, "-vn", "-c:a", "flac",
                            "-compression_level", "8", out_flac]))


def cut_wav16(ffmpeg, src_wav, out_wav, start, end):
    """切割 16k mono wav 供 whisper 转写"""
    run(ffmpeg_cmd(ffmpeg, ["-ss", f"{start:.3f}", "-to", f"{end:.3f}",
                            "-i", src_wav, "-vn", "-ar", "16000", "-ac", "1",
                            "-c:a", "pcm_s16le", out_wav]))


def detect_site(url):
    """按 URL 识别站点: bilibili / youtube / unknown"""
    u = (url or "").lower().strip()
    if "youtube.com" in u or "youtu.be" in u:
        return "youtube"
    if "bilibili.com" in u or u.startswith("bv"):
        return "bilibili"
    return "unknown"


def netscape_line(domain, name, value, exp, secure="TRUE", path="/"):
    """构造 Netscape cookies.txt 的一行 (yt-dlp 可解析)。value 中的控制字符需清洗。"""
    value = str(value).replace("\t", " ").replace("\r", " ").replace("\n", " ")
    return f"{domain}\tTRUE\t{path}\t{secure}\t{exp}\t{name}\t{value}"


def write_netscape_cookies(path, cookie_str, domain=".bilibili.com"):
    """把粘贴的 cookie 字符串 (如 'SESSDATA=xxx; bili_jct=yyy') 转成 yt-dlp 可用的 Netscape cookies.txt"""
    cookie_str = (cookie_str or "").strip()
    if cookie_str.lower().startswith("cookie:"):
        cookie_str = cookie_str[7:].strip()
    if not cookie_str:
        raise SystemExit("--cookies-text 为空")
    exp = str(int(__import__("time").time()) + 20 * 365 * 86400)
    lines = ["# Netscape HTTP Cookie File", "# generated by bili_split.py",
             netscape_line(domain, "_visited", "1", exp)]
    n = 0
    for pair in cookie_str.split(";"):
        pair = pair.strip()
        if "=" not in pair:
            continue
        k, v = pair.split("=", 1)
        k, v = k.strip(), v.strip()
        if not k:
            continue
        lines.append(netscape_line(domain, k, v, exp))
        n += 1
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    log(f"已从粘贴的 cookie 生成 {n} 个字段 -> {path}")


def find_node():
    for c in [NODE_DEFAULT, shutil.which("node")]:
        if c and os.path.exists(c):
            return c
    return None


def ytdlp_base(ytdlp, ffmpeg_bin, proxy, site, yt_client="android"):
    """yt-dlp 统一基础参数: ffmpeg 路径 / node JS runtime / 代理 / YouTube player client"""
    cmd = [ytdlp, "--no-playlist"]
    if ffmpeg_bin:
        cmd += ["--ffmpeg-location", ffmpeg_bin]
    node = find_node()
    if node:
        cmd += ["--js-runtimes", f"node:{node}"]
    if proxy:
        cmd += ["--proxy", proxy]
    if site == "youtube":
        # android: 代理 IP 下绕过 bot 检测(稳定但只有低清muxed); tv: 配 cookie 可解锁 1080p+128k 音频
        cmd += ["--extractor-args", f"youtube:player_client={yt_client}"]
    return cmd


def fmt_lrc_time(t):
    """秒 -> LRC 时间 [mm:ss.xx] (百分秒)"""
    m = int(t // 60)
    s = t - m * 60
    return f"{m:02d}:{s:05.2f}"


def to_simplified(text):
    """繁体转简体 (OpenCC t2s)。兼容 LRC: 保留 [时间戳]/[标签] 前缀, 只转文本部分。
    未安装 opencc 时原样返回。"""
    try:
        from opencc import OpenCC
        cc = OpenCC("t2s")
    except ImportError:
        return text
    out = []
    for line in (text or "").splitlines():
        if line.startswith("[") and "]" in line:
            i = line.index("]")
            out.append(line[:i + 1] + cc.convert(line[i + 1:]))
        else:
            out.append(cc.convert(line))
    return "\n".join(out)


def parse_vtt(path):
    """解析 YouTube 字幕 VTT -> [(绝对秒, 文本), ...] (官方歌词来源)"""
    cues = []
    ts = None
    parts = []
    for raw in open(path, encoding="utf-8"):
        line = raw.strip()
        if "-->" in line:
            if ts is not None and parts:
                cues.append((ts, " ".join(parts)))
            m = re.match(r"(\d+):(\d{2}):(\d{2}\.\d{3})\s*-->", line)
            ts = (int(m.group(1)) * 3600 + int(m.group(2)) * 60 + float(m.group(3))) if m else None
            parts = []
        elif line and not line.startswith(("WEBVTT", "Kind:", "Language:")):
            parts.append(line)
    if ts is not None and parts:
        cues.append((ts, " ".join(parts)))
    return cues


def fetch_subs(ytdlp, ffmpeg_bin, proxy, site, yt_client, args, tmp, lang):
    """下载 YouTube 官方字幕 (zh-Hant 等, android client 无需 PO token) -> vtt 路径"""
    cmd = ytdlp_base(ytdlp, ffmpeg_bin, proxy, site, yt_client) + [
        "--write-subs", "--sub-langs", lang, "--sub-format", "vtt",
        "--skip-download", "-o", os.path.join(tmp, "subs.%(ext)s"), args.url]
    try:
        subprocess.run(cmd, check=True, capture_output=True, text=True,
                       encoding="utf-8", errors="replace", timeout=300)
    except subprocess.CalledProcessError:
        return None
    for f in os.listdir(tmp):
        if f.startswith("subs.") and f.endswith(".vtt"):
            return os.path.join(tmp, f)
    return None


def collect_subs_timed(ytdlp, ffmpeg_bin, proxy, site, yt_client, args, tmp, segments, lang):
    """下载官方字幕并按分段切成相对时间戳歌词; 失败返回 None (调用方回退 Whisper)"""
    subs_path = fetch_subs(ytdlp, ffmpeg_bin, proxy, site, yt_client, args, tmp, lang)
    if not subs_path:
        log(f"官方字幕 {lang} 获取失败, 回退 Whisper 转写")
        return None
    cues = parse_vtt(subs_path)
    timed_map = {}
    for seg in segments:
        st, en = seg["start"], seg["end"]
        timed = [(round(t - st, 3), to_simplified(x)) for t, x in cues if st <= t < en]
        if timed:
            timed_map[seg["idx"]] = timed
    log(f"官方字幕 {lang} 可用 ({len(cues)} 条 cue), 跳过 Whisper 转写")
    return timed_map


def build_lrc(segments, title="", artist="", album=""):
    """带时间戳的转写结果 -> LRC 同步歌词文本 (标准头 [ti:][ar:][al:] + [mm:ss.xx] 行)

    标准头必须写全: 网易云音乐等国产播放器解析 LYRICS 时需要 [ti:][ar:][al:] 头
    (参考 MusicTag 写入格式: [ti:歌名]\\n[ar:歌手]\\n[al:专辑]\\n[00:00.00]...)
    """
    lines = []
    if title:
        lines.append(f"[ti:{title}]")
    if artist:
        lines.append(f"[ar:{artist}]")
    if album:
        lines.append(f"[al:{album}]")
    for start, text in segments:
        lines.append(f"[{fmt_lrc_time(start)}]{text}")
    return "\n".join(lines)


def rebuild_lrc_header(lrc, theme="", title_hint=""):
    """重建 LRC 标准头: 去掉旧 [xx:] 头, 用主题/标题写全 [ti:][ar:][al:] (网易云兼容)"""
    body = []
    for line in (lrc or "").splitlines():
        s = line.strip()
        if s.startswith("[") and "]" in s:
            tag = s[1:s.index("]")]
            if re.match(r"^(ti|ar|al|by|offset|la|re|ve|au|length)$", tag, re.I):
                continue  # 跳过旧头部标签
        body.append(line)
    header = f"[ti:{theme}]" if theme else ""
    if title_hint:
        header += f"\n[ar:{title_hint}]"
        header += f"\n[al:{title_hint}]"
    return (header + "\n" + "\n".join(body)).strip() if header else "\n".join(body)


def fetch_title(ytdlp, url, ffmpeg_bin, proxy, site, yt_client="android"):
    """用 yt-dlp 取视频标题（不下载）"""
    cmd = ytdlp_base(ytdlp, ffmpeg_bin, proxy, site, yt_client) + \
        ["--skip-download", "--print", "%(title)s", url]
    try:
        r = subprocess.run(cmd, capture_output=True, text=True,
                           encoding="utf-8", errors="replace", timeout=90)
        if r.returncode == 0 and r.stdout.strip():
            return r.stdout.strip().splitlines()[0]
    except Exception:
        pass
    return ""


def build_dl_cmd(ytdlp, ffmpeg_bin, proxy, site, yt_client, args, tmp, fmt):
    dl_cmd = ytdlp_base(ytdlp, ffmpeg_bin, proxy, site, yt_client) + \
        ["-f", fmt, "-o", os.path.join(tmp, "audio.%(ext)s")]
    if args.cookies_text:
        domain = ".youtube.com" if site == "youtube" else ".bilibili.com"
        write_netscape_cookies(os.path.join(tmp, "cookies.txt"), args.cookies_text, domain)
        dl_cmd += ["--cookies", os.path.join(tmp, "cookies.txt")]
    elif args.cookies:
        dl_cmd += ["--cookies", args.cookies]
    elif args.browser:
        dl_cmd += ["--cookies-from-browser", args.browser]
    dl_cmd += [args.url]
    return dl_cmd


def download_audio(ytdlp, ffmpeg_bin, proxy, site, yt_client, args, tmp, fmt):
    """下载最佳音轨到 tmp/audio.*。

    YouTube 走多 client 轮询自动降级 (当前 client -> web -> android -> tv),
    规避代理 IP 下的 bot 检测/限流; 全部失败则抛出最后一个错误。
    """
    if site != "youtube":
        run(build_dl_cmd(ytdlp, ffmpeg_bin, proxy, site, yt_client, args, tmp, fmt))
        return
    order = []
    for c in (yt_client, "web", "android", "tv"):
        if c not in order:
            order.append(c)
    last_err = None
    for c in order:
        try:
            run(build_dl_cmd(ytdlp, ffmpeg_bin, proxy, site, c, args, tmp, fmt))
            return
        except subprocess.CalledProcessError as e:
            last_err = e
            log(f"{c} client 下载失败, 尝试下一个 client...")
    raise last_err


# ---------------- 阶段一: split ----------------

def cmd_split(args):
    ffmpeg = find_exe("ffmpeg", args.ffmpeg, FFMPEG_DEFAULT)
    ytdlp = find_exe("yt-dlp", args.ytdlp, YTDLP_DEFAULT)
    cuts = parse_cuts(args.cuts)
    outdir = os.path.abspath(args.out)
    os.makedirs(outdir, exist_ok=True)
    tmp = os.path.join(outdir, "temp")
    os.makedirs(tmp, exist_ok=True)

    site = detect_site(args.url)
    log(f"站点识别: {site} | {args.url}")
    # YouTube 默认走本机代理 (国内直连被墙); 也可 --proxy 显式指定
    proxy = args.proxy
    if not proxy and site == "youtube":
        proxy = "http://127.0.0.1:7890"
        log(f"YouTube 检测, 自动使用代理 {proxy} (可用 --proxy 覆盖)")

    # 0. 先取标题（apply 阶段写 artist 标签）
    ffmpeg_bin = os.path.dirname(ffmpeg)
    has_cookie = bool(args.cookies or args.cookies_text or args.browser)
    yt_client = args.yt_client or ("tv" if (site == "youtube" and has_cookie) else "android")
    title = fetch_title(ytdlp, args.url, ffmpeg_bin, proxy, site, yt_client)
    log(f"视频标题: {title or '(获取失败)'}")

    # 1. 下载最佳音轨 (YouTube 多 client 轮询: 当前client -> web -> android -> tv)
    log(f"下载音轨: {args.url}")
    download_audio(ytdlp, ffmpeg_bin, proxy, site, yt_client, args, tmp, args.format)
    audio = None
    for f in os.listdir(tmp):
        if f.startswith("audio."):
            audio = os.path.join(tmp, f)
    if not audio:
        raise SystemExit("下载失败: 未找到音轨文件")

    # 2. 解码为完整 wav（原采样率, 用于切 flac） + 16k mono（用于 whisper）
    full_hi = os.path.join(tmp, "full_hi.wav")
    full_16k = os.path.join(tmp, "full_16k.wav")
    run(ffmpeg_cmd(ffmpeg, ["-i", audio, "-vn", "-c:a", "pcm_s16le", full_hi]))
    run(ffmpeg_cmd(ffmpeg, ["-i", audio, "-vn", "-ar", "16000", "-ac", "1",
                            "-c:a", "pcm_s16le", full_16k]))

    # 3. 切割
    segments = []
    for i, (s, e) in enumerate(cuts, 1):
        tag = f"seg_{i:02d}"
        cut_flac(ffmpeg, full_hi, os.path.join(outdir, f"{tag}.flac"), s, e)
        cut_wav16(ffmpeg, full_16k, os.path.join(tmp, f"{tag}_w16.wav"), s, e)
        segments.append({"idx": i, "tag": tag, "start": s, "end": e,
                         "start_str": f"{s:.3f}", "end_str": f"{e:.3f}",
                         "theme": "", "lyrics_file": f"{tag}.txt"})

    with open(os.path.join(outdir, "cuts.json"), "w", encoding="utf-8") as f:
        json.dump({"url": args.url, "title_hint": title, "segments": segments},
                  f, ensure_ascii=False, indent=2)

    # 4. 歌词来源: 优先 YouTube 官方字幕(--subs-lang, 更准确), 否则 Whisper 转写
    subs_timed = None
    if args.subs_lang and site == "youtube":
        subs_timed = collect_subs_timed(ytdlp, ffmpeg_bin, proxy, site, yt_client,
                                        args, tmp, segments, args.subs_lang)

    log(f"加载 Whisper 模型: {args.model} (首次会自动下载, 走 hf-mirror 镜像)")
    from faster_whisper import WhisperModel
    model = WhisperModel(args.model, device="cpu", compute_type="int8")
    for seg in segments:
        wav16 = os.path.join(tmp, f"{seg['tag']}_w16.wav")
        txt = os.path.join(outdir, f"{seg['tag']}.txt")
        lrc_path = os.path.join(outdir, f"{seg['tag']}.lrc")
        log(f"转写 {seg['tag']} ({seg['start_str']} - {seg['end_str']}) ...")
        lang = args.lang or None
        if subs_timed and seg["idx"] in subs_timed:
            timed = subs_timed[seg["idx"]]
            info_lang = args.subs_lang
        else:
            seg_iter, info = model.transcribe(wav16, language=lang,
                                              beam_size=5, vad_filter=args.vad)
            timed = [(s.start, s.text.strip()) for s in seg_iter if s.text.strip()]
            info_lang = info.language
        text = "\n".join(t for _, t in timed)
        text = to_simplified(text)  # 繁体 -> 简体
        with open(txt, "w", encoding="utf-8") as f:
            f.write(text + "\n")
        # LRC 同步歌词 (embedded 滚动歌词; 标准头 [ti:][ar:][al:] + [mm:ss.xx] 时间戳)
        lrc = to_simplified(build_lrc(timed, title, artist=title, album=title))
        with open(lrc_path, "w", encoding="utf-8") as f:
            f.write(lrc + "\n")
        seg["lang"] = info_lang
        seg["lyrics_file"] = f"{seg['tag']}.txt"
        seg["lrc_file"] = f"{seg['tag']}.lrc"
        seg["lyrics_preview"] = text[:60].replace("\n", " / ")
        src = "字幕" if (subs_timed and seg["idx"] in subs_timed) else "whisper"
        log(f"  -> {len(text)} 字, {len(timed)} 句(带时间戳), 来源 {src}")

    # 5. 主题模板
    themes = os.path.join(outdir, "themes.json")
    with open(themes, "w", encoding="utf-8") as f:
        json.dump({"instructions": "为每段填 theme 字段(4-8字中文主题), 保存后运行 apply",
                   "segments": segments}, f, ensure_ascii=False, indent=2)
    log(f"完成! 输出目录: {outdir}")
    log(f"下一步: 读取各 seg_XX.txt 歌词, 填好 {themes} 的 theme, 再执行 apply")
    return outdir


def write_flac_tags(path, title="", artist="", lyrics_lrc="", comment="", lyrics_plain=""):
    """用 mutagen 写 FLAC Vorbis Comment 标签 (embedded 嵌入)。

    歌词字段说明 (FLAC 无官方字段, 两个事实标准):
      - LYRICS:            foobar2000 / MusicBee / Poweramp / MusicBrainz Picard 阵营
                           写入 LRC 同步歌词(带 [mm:ss.xx] 时间戳) -> 播放器逐行滚动
      - UNSYNCEDLYRICS:    Mp3tag / Bandcamp 阵营, 写入纯文本歌词(静态整块)
    双写以最大化兼容; 字段名必须大写 (小写 lyrics 多数播放器不认)。
    参考: MusicBrainz Picard 源码注释 "We read both but always write LYRICS"
    """
    from mutagen.flac import FLAC
    f = FLAC(path)
    if title:
        f["TITLE"] = [title]
    if artist:
        f["ARTIST"] = [artist]
    if lyrics_lrc:
        f["LYRICS"] = [lyrics_lrc]
    if lyrics_plain:
        f["UNSYNCEDLYRICS"] = [lyrics_plain]
    if comment:
        f["COMMENT"] = [comment]
    f.save()


# ---------------- 阶段二: apply ----------------

ILLEGAL = re.compile(r'[\\/:*?"<>|\r\n\t]')


def sanitize(name):
    return ILLEGAL.sub("_", name).strip().strip(".")


def cmd_apply(args):
    ffmpeg = find_exe("ffmpeg", args.ffmpeg, FFMPEG_DEFAULT)
    outdir = os.path.abspath(args.out)
    themes_path = args.themes or os.path.join(outdir, "themes.json")
    with open(themes_path, "r", encoding="utf-8") as f:
        data = json.load(f)
    cuts_path = os.path.join(outdir, "cuts.json")
    meta = {}
    if os.path.exists(cuts_path):
        with open(cuts_path, "r", encoding="utf-8") as f:
            meta = json.load(f)
    url = meta.get("url", "")

    for seg in data["segments"]:
        theme = (seg.get("theme") or "").strip()
        if not theme:
            log(f"跳过 {seg['tag']}: 未填主题")
            continue
        tag = seg["tag"]
        src = os.path.join(outdir, f"{tag}.flac")
        if not os.path.exists(src):
            log(f"跳过 {tag}: 找不到 {src}")
            continue
        # 歌词文本
        lyrics = ""
        lf = os.path.join(outdir, seg.get("lyrics_file", f"{tag}.txt"))
        if os.path.exists(lf):
            with open(lf, "r", encoding="utf-8") as f:
                lyrics = f.read().strip()
        # LRC 同步歌词 (滚动)
        lrc = ""
        lrcf = os.path.join(outdir, seg.get("lrc_file", f"{tag}.lrc"))
        if os.path.exists(lrcf):
            with open(lrcf, "r", encoding="utf-8") as f:
                lrc = f.read().strip()
        if not lrc:
            lrc = lyrics  # 兜底: 无时间戳时降级为纯文本
        # 重建标准 LRC 头 (网易云兼容: [ti:歌名][ar:][al:] 必须写全)
        lrc = rebuild_lrc_header(lrc, theme, meta.get("title_hint", ""))
        # 目标名: NN_主题.flac
        num = f"{seg.get('idx', 0):02d}"
        dst = os.path.join(outdir, f"{num}_{sanitize(theme)}.flac")
        # 1) ffmpeg 纯拷贝改名 (不写 metadata, 保持流完整)
        run(ffmpeg_cmd(ffmpeg, ["-i", src, "-c", "copy", dst]))
        # 2) mutagen 写标签 (embedded): LYRICS=LRC滚动歌词, UNSYNCEDLYRICS=纯文本
        comment = f"源:{url} 段:{seg.get('start_str','')}-{seg.get('end_str','')}"
        write_flac_tags(dst, theme, meta.get("title_hint", ""), lrc, comment, lyrics)
        try:
            os.remove(src)
        except OSError as e:
            log(f"警告: 删除中间文件失败(可手动删): {src} ({e})")
        log(f"{tag}.flac -> {os.path.basename(dst)} (LYRICS 同步歌词 {len(lrc.splitlines())} 行 / UNSYNCEDLYRICS {len(lyrics)} 字)")
    log("apply 完成")


# ---------------- fetch-model: 下载 whisper 模型到本地 ----------------

def cmd_fetch(args):
    """下载 Systran/faster-whisper-<name> 到 models/ 目录（国内镜像优先, 失败切代理官方源）"""
    import ssl
    name = args.name
    dst_dir = os.path.join(args.dir, f"faster-whisper-{name}")
    os.makedirs(dst_dir, exist_ok=True)
    files = ["config.json", "model.bin", "tokenizer.json", "vocabulary.txt"]
    bases = [(f"https://hf-mirror.com/Systran/faster-whisper-{name}/resolve/main/", None),
             (f"https://huggingface.co/Systran/faster-whisper-{name}/resolve/main/", "http://127.0.0.1:7890")]
    socket.setdefaulttimeout(30)
    for fn in files:
        dst = os.path.join(dst_dir, fn)
        if os.path.exists(dst) and os.path.getsize(dst) > 0:
            log(f"跳过已有 {fn}")
            continue
        ok = False
        for base, proxy in bases:
            url = base + fn
            try:
                op = urllib.request.build_opener(
                    urllib.request.ProxyHandler({"https": proxy}) if proxy else urllib.request.ProxyHandler({}))
                with op.open(url, timeout=1800) as r, open(dst, "wb") as f:
                    f.write(r.read())
                log(f"OK {fn} ({os.path.getsize(dst)}B) via {url.split('/')[2]}")
                ok = True
                break
            except Exception as e:
                log(f"FAIL {fn} via {url.split('/')[2]}: {type(e).__name__}")
        if not ok:
            raise SystemExit(f"下载失败: {fn}")
    log(f"模型就绪: {dst_dir} (在 split 时用 --model 指定此目录)")


# ---------------- import-cookies: EditThisCookie JSON -> cookies.txt ----------------

def cmd_import_cookies(args):
    """把浏览器扩展导出的 cookie (EditThisCookie JSON 数组 或 name=value; 字符串) 转成 yt-dlp 的 cookies.txt"""
    with open(args.input, "r", encoding="utf-8") as f:
        data = json.load(f)
    if isinstance(data, str):
        # 形如 "SESSDATA=xxx; bili_jct=yyy" 的原始字符串
        write_netscape_cookies(args.output, data, domain=args.domain or ".youtube.com")
        return
    items = data if isinstance(data, list) else data.get("cookies", [])
    if not isinstance(items, list):
        raise SystemExit(f"无法识别的 cookie 格式: {args.input}")
    lines = ["# Netscape HTTP Cookie File", "# generated by bili_split.py import-cookies"]
    n = 0
    for c in items:
        if not isinstance(c, dict):
            continue
        name, value = c.get("name", ""), c.get("value", "")
        if not name:
            continue
        domain = c.get("domain", "") or args.domain or ".youtube.com"
        if not domain.startswith("."):
            domain = "." + domain
        path = c.get("path", "/") or "/"
        secure = "TRUE" if c.get("secure") else "FALSE"
        exp = int(c.get("expirationDate", 0)) if c.get("expirationDate") else 0
        lines.append(netscape_line(domain, name, value, exp, secure, path))
        n += 1
    with open(args.output, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    log(f"已从 {args.input} 导入 {n} 条 cookie -> {args.output} (注意: 文件含登录凭证, 勿外传/勿入库)")


# ---------------- 自测 ----------------

def cmd_selftest(args):
    """合成 3 段正弦波音频, 跑完整切割+转写+标签链路, 验证工具链可用"""
    ffmpeg = find_exe("ffmpeg", args.ffmpeg, FFMPEG_DEFAULT)
    tmp = tempfile.mkdtemp(prefix="bili_selftest_")
    wav = os.path.join(tmp, "synth.wav")
    sr, dur = 16000, 9
    import math
    import struct
    with wave.open(wav, "wb") as w:
        w.setnchannels(1)
        w.setsampwidth(2)
        w.setframerate(sr)
        frames = bytearray()
        for n in range(sr * dur):
            v = int(12000 * math.sin(2 * math.pi * (440 if n % 3 == 0 else 554) * n / sr))
            frames += struct.pack("<h", v)
        w.writeframes(bytes(frames))
    log("自测: 切割 0-3/3-6/6-9 三段 -> flac + 转写(模型 " + args.model + ")")
    from faster_whisper import WhisperModel
    model = WhisperModel(args.model, device="cpu", compute_type="int8")
    for i, (s, e) in enumerate([(0, 3), (3, 6), (6, 9)], 1):
        tag = f"seg_{i:02d}"
        cut_flac(ffmpeg, wav, os.path.join(tmp, f"{tag}.flac"), s, e)
        cut_wav16(ffmpeg, wav, os.path.join(tmp, f"{tag}_w16.wav"), s, e)
        segments, info = model.transcribe(os.path.join(tmp, f"{tag}_w16.wav"),
                                          beam_size=5, vad_filter=True)
        txt = " ".join(x.text for x in segments)
        log(f"{tag}: 时长3s flac={os.path.getsize(os.path.join(tmp, tag+'.flac'))}B 转写={txt[:40]!r}")
    log("自测通过: 工具链可用")
    shutil.rmtree(tmp, ignore_errors=True)


# ---------------- main ----------------

def main():
    ap = argparse.ArgumentParser(description="B站/YouTube 视频分段 + FLAC + Whisper 歌词 + 主题命名")
    sub = ap.add_subparsers(dest="cmd", required=True)

    p_split = sub.add_parser("split", help="下载→切割→转写歌词")
    p_split.add_argument("--url", required=True)
    p_split.add_argument("--cuts", required=True, help="每段起止, 逗号分隔, 如 '0:00-12:34, 12:34-25:00'")
    p_split.add_argument("--model", default="small", help="whisper 模型: tiny/base/small/medium (中文建议 small/medium)")
    p_split.add_argument("--lang", default=None, help="识别语言, 默认自动 (中文可指定 zh)")
    p_split.add_argument("--vad", action="store_true",
                         help="开启 VAD 静音过滤 (讲课类可开; 默认关闭以免过滤掉音乐/人声)")
    p_split.add_argument("--subs-lang", default=None,
                         help="优先用 YouTube 官方字幕作歌词 (如 zh-Hant, 比 Whisper 准确; 获取失败自动回退)")
    p_split.add_argument("--out", default="./output")
    p_split.add_argument("--browser", default=None, help="如 edge, 用浏览器登录态下载高清音轨")
    p_split.add_argument("--cookies", default=None, help="Netscape 格式 cookies.txt 文件路径 (B站高清需登录)")
    p_split.add_argument("--cookies-text", default=None,
                         help="直接粘贴的 B 站 cookie 字符串, 如 'SESSDATA=xxx; bili_jct=yyy' (优先于 --cookies/--browser)")
    p_split.add_argument("--proxy", default=None,
                         help="下载代理, 如 http://127.0.0.1:7890 (YouTube 未指定时自动默认本机代理)")
    p_split.add_argument("--format", default="bestaudio/best",
                         help="yt-dlp 格式选择器, 默认 bestaudio/best (YouTube 想省流量可试 worst[acodec!=none])")
    p_split.add_argument("--yt-client", default=None,
                         help="YouTube player client: android(默认,免cookie) / tv(配cookie解锁高画质)")
    p_split.add_argument("--ffmpeg", default=None)
    p_split.add_argument("--ytdlp", default=None)

    p_apply = sub.add_parser("apply", help="填好主题后: 重命名+嵌入歌词标签")
    p_apply.add_argument("--out", default="./output")
    p_apply.add_argument("--themes", default=None)
    p_apply.add_argument("--ffmpeg", default=None)

    p_test = sub.add_parser("selftest", help="离线自测工具链")
    p_test.add_argument("--model", default="tiny")
    p_test.add_argument("--ffmpeg", default=None)

    p_fetch = sub.add_parser("fetch-model", help="下载 whisper 模型到本地 (镜像优先)")
    p_fetch.add_argument("--name", default="small", help="tiny/base/small/medium/large-v3")
    p_fetch.add_argument("--dir", default=os.path.join(os.path.dirname(os.path.abspath(__file__)), "models"))

    p_imp = sub.add_parser("import-cookies", help="浏览器导出的 cookie JSON -> yt-dlp cookies.txt")
    p_imp.add_argument("--input", required=True, help="cookie JSON 文件 (EditThisCookie 格式)")
    p_imp.add_argument("--output", default="cookies.txt")
    p_imp.add_argument("--domain", default=None, help="缺省域名 (JSON 无 domain 字段时用)")

    args = ap.parse_args()
    if args.cmd == "split":
        cmd_split(args)
    elif args.cmd == "apply":
        cmd_apply(args)
    elif args.cmd == "selftest":
        cmd_selftest(args)
    elif args.cmd == "fetch-model":
        cmd_fetch(args)
    elif args.cmd == "import-cookies":
        cmd_import_cookies(args)


if __name__ == "__main__":
    main()
